# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Payrexx Payment App"
client_id = "719e4fe2e4f17facb40b68c496f9b697"
application_url = "https://7266-94-154-224-44.ngrok-free.app"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_gateways,write_payment_sessions"

[auth]
redirect_urls = [
  "https://7266-94-154-224-44.ngrok-free.app/auth/callback",
  "https://7266-94-154-224-44.ngrok-free.app/auth/shopify/callback",
  "https://7266-94-154-224-44.ngrok-free.app/api/auth/callback",
  "https://7266-94-154-224-44.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "payrexx-test.myshopify.com"
