import type {Localization} from "~/types";
export const localizationData : Localization = {
  EN: {
    flag: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 30" width="35" height="18"><clipPath id="a"><path d="M0 0v30h60V0z"/></clipPath><clipPath id="b"><path d="M30 15h30v15zv15H0zH0V0zV0h30z"/></clipPath><g clip-path="url(#a)"><path d="M0 0v30h60V0z" fill="#012169"/><path d="m0 0 60 30m0-30L0 30" stroke="#fff" stroke-width="6"/><path d="m0 0 60 30m0-30L0 30" clip-path="url(#b)" stroke="#C8102E" stroke-width="4"/><path d="M30 0v30M0 15h60" stroke="#fff" stroke-width="10"/><path d="M30 0v30M0 15h60" stroke="#C8102E" stroke-width="6"/></g></svg>',
    PLUGIN_TITLE: 'Payrexx Plugin for Shopify',
    SECTION_TITLE_CREDENTIALS: 'API Settings',
    CREDENTIALS_DESCRIPTION: 'Please enter a valid combination of these three settings to get access to the rest of the settings.',
    REQUIRED: 'Required',
    PLATFORM_KEY: 'Platform',
    INSTANCE_NAME_KEY: 'Instance Name',
    API_KEY: 'API Key',
    INSTANCE_DESCRIPTION: 'The instance name is your Payrexx account name. You can find it at the start of the URL when being logged in to your dashboard: instance-name.payrexx.com.',
    API_DESCRIPTION: 'You can find your API key in the section "API & Integration" of your Payrexx dashboard. Please make sure that you copy the key from the Shopify integration details.',
    SECTION_TITLE_DESIGN: 'Design Settings',
    OPTIONAL: 'Optional',
    DESIGN_KEY: 'Look and Feel Profile',
    DESIGN_DESCRIPTION: 'The look and feel profile defines the appearance of the payment page.',
    PAYMENT_METHODS: 'Payment Methods',
    PAYMENT_METHODS_INFO: 'Please note that it is not possible to specify which payment methods available in this plugin are enabled - Shopify does not provide the required means. Enable all payment methods available in this plugin to provide the best user experience. Otherwise, the customer will be presented with Visa, for example, which cannot be selected on the payment page afterwards.',
    TITLE_HELP: 'Help',
    DESCRIPTION_HELP: 'Further information about integration Payrexx into your Shopify store can be found in our documentation.',
    SUPPORT_SYSTEM: 'Documentation',
    CANCEL: 'Cancel',
    SAVE: 'Save',
  },
  DE: {
    flag: '<svg xmlns="http://www.w3.org/2000/svg" width="30" height="18" viewBox="0 0 5 3"><path d="M0 0h5v3H0z"/><path fill="#D00" d="M0 1h5v2H0z"/><path fill="#FFCE00" d="M0 2h5v1H0z"/></svg>',
    PLUGIN_TITLE: 'Payrexx Plugin für Shopify',
    SECTION_TITLE_CREDENTIALS: 'API Einstellungen',
    CREDENTIALS_DESCRIPTION: 'Bitte geben Sie eine gültige Kombination dieser drei Einstellungen ein, um Zugang zu den restlichen Einstellungen zu erhalten.',
    REQUIRED: 'Erforderlich',
    PLATFORM_KEY: 'Plattform',
    INSTANCE_NAME_KEY: 'Instanzname',
    API_KEY: 'API Schlüssel',
    INSTANCE_DESCRIPTION: 'Der Instanzname ist der Name Ihres Payrexx-Kontos. Sie finden ihn am Anfang der URL, wenn Sie in Ihrem Dashboard angemeldet sind: instance-name.payrexx.com.',
    API_DESCRIPTION: 'Sie finden Ihren API-Schlüssel im Bereich "API & Integration" Ihres Payrexx Dashboards. Bitte stellen Sie sicher, dass Sie den Schlüssel aus den Shopify-Integrationsdetails kopieren.',
    SECTION_TITLE_DESIGN: 'Design Einstellungen',
    OPTIONAL: 'Optional',
    DESIGN_KEY: 'Look-and-Feel Profil',
    DESIGN_DESCRIPTION: 'Das Look-and-Feel Profil bestimmt das Erscheinungsbild der Zahlungsseite.',
    PAYMENT_METHODS: 'Zahlungsmethoden',
    PAYMENT_METHODS_INFO: 'Bitte beachten Sie, dass nicht festgelegt werden kann, welche in diesem Plugin zur Verfügung stehenden Zahlungsmethoden aktiviert sind - Shopify bietet die benötigten Mittel nicht. Aktivieren Sie alle in diesem Plugin stehenden Zahlungsmethoden, um die beste Benutzererfahrung zu ermöglichen. Sonst wird dem Kunden/der Kundin beispielsweise Visa im Shopify Checkout dargestellt, was nachher auf der Zahlungsseite nicht ausgewählt werden kann.',
    TITLE_HELP: 'Hilfe',
    DESCRIPTION_HELP: 'Weitere Informationen zur Integration von Payrexx in Ihren Shopify-Shop finden Sie in unserer Dokumentation.',
    SUPPORT_SYSTEM: 'Dokumentation',
    CANCEL: 'Abbrechen',
    SAVE: 'Speichern',
  },
  FR: {
    flag: '<svg xmlns="http://www.w3.org/2000/svg" width="30" height="18" viewBox="0 0 900 600"><path fill="#ED2939" d="M0 0h900v600H0z"/><path fill="#fff" d="M0 0h600v600H0z"/><path fill="#002395" d="M0 0h300v600H0z"/></svg>',
    PLUGIN_TITLE: 'Payrexx Plugin pour Shopify',
    SECTION_TITLE_CREDENTIALS: 'Paramètres de l\'API',
    CREDENTIALS_DESCRIPTION: 'Veuillez entrer une combinaison valide de ces trois paramètres pour accéder au reste des paramètres.',
    REQUIRED: 'Requis',
    PLATFORM_KEY: 'Plateforme',
    INSTANCE_NAME_KEY: 'Nom de l\'instance',
    API_KEY: 'Clé API',
    INSTANCE_DESCRIPTION: 'Le nom d\'instance est le nom de votre compte Payrexx. Vous le trouverez au début de l\'URL lorsque vous êtes connecté à votre tableau de bord : instance-name.payrexx.com.',
    API_DESCRIPTION: 'Vous trouverez votre clé API dans la section "API & intégration" de votre tableau de bord Payrexx. Veuillez vous assurer de copier la clé depuis les détails d\'intégration Shopify.',
    SECTION_TITLE_DESIGN: 'Paramètres de conception',
    OPTIONAL: 'Optionnel',
    DESIGN_KEY: 'Profil Look-and-Feel',
    DESIGN_DESCRIPTION: 'Le profil Look-and-Feel détermine l\'apparence de la page de paiement.',
    PAYMENT_METHODS: 'Modes de paiement',
    PAYMENT_METHODS_INFO: 'Veuillez noter qu\'il n\'est pas possible de spécifier quelles méthodes de paiement sont activées dans ce plugin - Shopify ne fournit pas les moyens de le faire. Activez toutes les méthodes de paiement disponibles dans ce plugin pour offrir la meilleure expérience utilisateur. Sinon, le client se verra présenter, par exemple, Visa lors du paiement Shopify, qui ne pourra pas être sélectionné par la suite sur la page de paiement.',
    TITLE_HELP: 'Aide',
    DESCRIPTION_HELP: 'Vous trouverez plus d\'informations sur l\'intégration de Payrexx dans votre Shopify-Shop dans notre documentation.',
    SUPPORT_SYSTEM: 'Documentation',
    CANCEL: 'Annuler',
    SAVE: 'Enregistrer',
  }
}

